### ISSUE TITLE
[Bug] Login problem EU

### ISSUE THREAD

**Issue by alessandrorebosio** [greghesp/ha-bambulab#705] opened 2024-11-07 09:35 UTC
### Describe the bug

![IMG_0048](https://github.com/user-attachments/assets/66f21cc8-17a9-4b88-8b29-0f6b8fbe008f)
![IMG_0047](https://github.com/user-attachments/assets/c1becdf3-926b-4177-b5cd-489880c02e3c)

Version: 2.0.32

### To Reproduce

1. Select Europe
2. Input e-mail and password
3. Click next 
ERROR

### Expected Behaviour

Login successfully

### What device are you using?

P1S

### Diagnostic Output

```shell
LOGIN ATTEMPT FAILED: 403
This error originated from a custom integration.

Logger: custom_components.bambu_lab.pybambu
Source: custom_components/bambu_lab/pybambu/bambu_cloud.py:65
integration: Bambu Lab (documentation, issues)
First occurred: 10:32:28 AM (1 occurrences)
Last logged: 10:32:28 AM

Login attempt failed with error code: 403

FAILED TO CONNECT 
This error originated from a custom integration.

Logger: custom_components.bambu_lab
Source: custom_components/bambu_lab/config_flow.py:153
integration: Bambu Lab (documentation, issues)
First occurred: 10:32:28 AM (1 occurrences)
Last logged: 10:32:28 AM

Failed to connect with error code (403,)
```

### Log Extracts

```shell
2024-11-07 10:32:28.839 ERROR (SyncWorker_6) [custom_components.bambu_lab.pybambu] Login attempt failed with error code: 403
2024-11-07 10:32:28.841 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code (403,)
```

**Comment by geofffarmer** [comment] 2024-11-07 11:53
I have this issue too

**Comment by TwoPlayer** [comment] 2024-11-07 12:32
Got the same issue, that's the debug log:
```2024-11-07 13:29:36.539 DEBUG (SyncWorker_2) [custom_components.bambu_lab.pybambu] login()
2024-11-07 13:29:36.539 DEBUG (SyncWorker_2) [custom_components.bambu_lab.pybambu] Getting accessToken from Bambu Cloud
2024-11-07 13:29:36.810 ERROR (SyncWorker_2) [custom_components.bambu_lab.pybambu] Login attempt failed with error code: 403
2024-11-07 13:29:36.811 DEBUG (SyncWorker_2) [custom_components.bambu_lab.pybambu] Response: '<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" /><![endif]-->
<style>body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!-->
<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>
<!--<![endif]-->


</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> bambulab.com</h2>
      </div><!-- /.header -->

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
            
              <span class="cf-no-screenshot error"></span>
            
          </div>
        </div>
      </div><!-- /.captcha-container -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">8ded5470a855c7df</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">81.173.157.189</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script>
  window._cf_translation = {};
  
  
</script>

<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'8ded5470a855c7df',t:'MTczMDk4MjU3Ni4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body>
</html>
'
2024-11-07 13:29:36.812 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code (403,)```

**Comment by stoykengesicht** [comment] 2024-11-07 13:18
I have the same problem , no way to login from ,,EU" .. inncorrect logging information. It's the correct information.

**Comment by Schokobecher** [comment] 2024-11-07 13:24
Seems like we are getting blocked by Cloudflare, I use the _Other_ region, and get the same Cloudflare 403 response.

**Comment by stoykengesicht** [comment] 2024-11-07 13:28
Thanks for the very fast answer, Unfortunately, it doesn't work in other regions either. It always says the login information is wrong, despite checkingmfg und bleiben Sie gesundChristoph StoykeAm 07.11.24, 14:24 schrieb Pierre ***@***.***>:

Seems like we are getting blocked by Cloudflare, I use the Other region, and get the same Cloudflare 403 response.

**Comment by TwoPlayer** [comment] 2024-11-07 13:29
The reasoning is discussed here: #702

**Comment by 403-Forbidde** [comment] 2024-11-07 13:45
Same T.T
v2.0.32
Same T.T
Cannt login from China 
Sorry, you have been blocked……

**Comment by Dogmiester** [comment] 2024-11-07 19:37
Same issue - North America
Incorrect login information - it is correct!

**Comment by mshrem** [comment] 2024-11-07 22:19
Having the same issue in NA

**Comment by AdrianGarside** [comment] 2024-11-07 23:19
Dupe of #702

**Closed by AdrianGarside** 2024-11-07 23:19 UTC
Labels: bug

**Comment by AdrianGarside** [comment] 2024-11-08 04:53
New fix attempt: https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.33

**Comment by buliwyf42** [comment] 2024-11-08 07:04
This did the trick. Login is possible. After that i'm asked for a local connection which does not work. If i configure the Plugin as Local Lan it does not work either.

**Comment by martsmall** [comment] 2024-11-08 08:03
> This did the trick. Login is possible. After that i'm asked for a local connection which does not work. If i configure the Plugin as Local Lan it does not work either.

I had the same problem, for some reason the x1c was showing the wrong IP address on the printer , I got the ip from my router and worked

**Comment by buliwyf42** [comment] 2024-11-08 08:54
> > This did the trick. Login is possible. After that i'm asked for a local connection which does not work. If i configure the Plugin as Local Lan it does not work either.
> 
> I had the same problem, for some reason the x1c was showing the wrong IP address on the printer , I got the ip from my router and worked

It works now. It appears that the UDMP applied the Guest Notwork rules despite the fact i put the device not in the guest network.

**Comment by Dogmiester** [comment] 2024-11-08 15:19
Working great, now. TY
