### ISSUE TITLE
[Bug] Sensors switched to "unknown" while not printing

### ISSUE THREAD

**Issue by busaku** [greghesp/ha-bambulab#142] opened 2023-05-13 08:31 UTC
### Describe the bug

All sensors randomly switched to "unknown" while not printing.

<img width="360" alt="image" src="https://github.com/greghesp/ha-bambulab/assets/25269085/ce0e3d4d-4db1-4dfc-8a9e-61a1b09dfa6d">

<img width="542" alt="image" src="https://github.com/greghesp/ha-bambulab/assets/25269085/2af0bbb2-9934-4f07-b24b-c3984345bc44">

<img width="677" alt="image" src="https://github.com/greghesp/ha-bambulab/assets/25269085/94d1a9b7-6b6a-47c2-8900-dd12af1a7ffd">

### To Reproduce

1. just print something
2. wait until it happens

### Expected Behaviour

Should not switched to unknown

### What device are you using?

X1C

### Firmware Version

01.05.01

### Home Assistant Version

2023.5.2

### Component Version

1.2.1

**Comment by busaku** [comment] 2023-05-13 08:32
Okay, in this second I got the component update to 1.3.1
I will report if the error is still there.
Thanks for your work here :)

**Comment by mattkerrison** [comment] 2023-05-15 02:49
Yep got the same issue with 1.3.1 version

**Comment by WolfwithSword** [comment] 2023-06-04 13:10
Is it happening to all sensors or just a select few? From the screenshots it looks like it's only happening to some specific ones (layer info, end time, and then weirdly current stage is doing it when transitioning between stages).

Should also note, that at least for sensors in HA, "Unavailable" is a very different state from "Unknown". When it's unavailable it means there's nothing to provide data for it and it's as if it's absent, whereas unknown is it's present but without value. From the looks of it, you're getting unavailable.

For the layer information, it would be cleared on print finish and not relevant, hence why that is unavailable since you're no longer printing. If it happens to all sensors then it would definitely be a bug. For end time, I'm not sure if it would persist when a print finishes or not. But definitely if print stage is switching instantly from unavailable to something else, there is an issue with that, though I would consider that minor since it appears to always come back instantly.

**Comment by mydevpeeps** [comment] 2023-06-29 12:51
**Confirmation**
For me it only happens for the Current Stage sensor:
![image](https://github.com/greghesp/ha-bambulab/assets/25742242/50119d0f-e063-4c79-b73b-f03793dee391)

**Additional Thoughts**
I am not in LAN Only mode (in case it matters). My X1C does also show other sensors as unknown when nothing is going on. However, they are attributes I'm using to create sensors with seem to be the items that go to an unknown state. They don't actually have a value at all when there is nothing there. If the response back from the printer doesn't have the information the integration is not doing anything wrong in displaying them as unknown in my opinion.

![image](https://github.com/greghesp/ha-bambulab/assets/25742242/d8a2ff75-be94-4bbb-8fe0-f0b73f6141d4)

``` 
  - sensor:
    - name: x1c_right_hms_count
      state: "{{ state_attr('binary_sensor.bambu_right_x1c_hms_errors', 'Count') }}"
  - sensor:
    - name: x1c_right_hms_1_error
      state: "{{ state_attr('binary_sensor.bambu_right_x1c_hms_errors', '1-Error') }}"
  - sensor:
    - name: x1c_right_hms_1_wiki
      state: "{{ state_attr('binary_sensor.bambu_right_x1c_hms_errors', '1-Wiki') }}"
  - sensor:
    - name: x1c_right_hms_2_error
      state: "{{ state_attr('binary_sensor.bambu_right_x1c_hms_errors', '2-Error') }}"
  - sensor:
    - name: x1c_right_hms_2_wiki
      state: "{{ state_attr('binary_sensor.bambu_right_x1c_hms_errors', '2-Wiki') }}"
```

![image](https://github.com/greghesp/ha-bambulab/assets/25742242/2c733748-7a10-4101-90fa-299e63a4b4b6)

**Conclusion**
This all makes me wonder if the OP is not getting this data back from the queries to the printer. Can this be confirmed in logs?

**Comment by WolfwithSword** [comment] 2023-06-29 13:07
Interesting analysis. It's strange the current_stage is unknown, it could be maybe the numerical key for it is an unexpected value erroring on translation now? Are you on latest firmware?

LAN Only mode (or lack of it) shouldn't have any difference for the X1C at least, so that's good to rule out. I'm unsure about the logging, but it is possible to use a tool such as mqtt-explorer to connect directly to the printer and see what is raw/being sent to the integration every second.

From OP's images, it seemed like it was mostly for expected sensors, aside from current stage going unknown when transitioning between states, so it leads me to believe it's mostly on processing the payload from printer. But for @mydevpeeps  the current stage is unknown in general, which is a bit alarming hence I ask if you're on newest firmware. Never know if they added some additional numerical state lol. If so it would likely also be in the bambu-studio code, as that is where the original translations come from.

**Comment by AdrianGarside** [comment] 2023-07-16 20:24
@busaku I think I fixed this a short while back. Can you confirm if you are still seeing this?

**Comment by AdrianGarside** [comment] 2023-07-17 00:08
If this was still occurring, I believe is will be fixed in https://github.com/greghesp/ha-bambulab/releases/tag/v1.4.4-dev

**Closed by AdrianGarside** 2023-07-17 00:08 UTC
Labels: bug
