### ISSUE TITLE
[Bug] Renaming the integration breaks the functionality and everything becomes unavailable.

### ISSUE THREAD

**Issue by LayerCakeMakes** [greghesp/ha-bambulab#57] opened 2023-03-25 17:36 UTC
### Describe the bug

When the integration gets renamed to a friendlier name than the printers serial number the functionality breaks and it stops working.

### To Reproduce

1. Go to the integrations
2. Hit the 3 dots on the Printer integration and select rename

### Expected Behaviour

The printer integration should remain functional after the renaming.

### What device are you using?

X1C

### Firmware Version

00.00.17.74

### Home Assistant Version

2023.3.6

### Component Version

3c054df

**Comment by LayerCakeMakes** [comment] 2023-03-25 18:13
I've tried changing the name back to what it was but it remains broken even with the original name after it was changed once.

**Comment by carltonwb** [comment] 2023-03-26 14:49
Same issue. If I rename the device it lists all items as unavailable.
If I try to rename back to original it still shows as unavailable.
There is nothing in the log file in regards to this.
I tried it on all of my 4 printers and they all do the same.
Please let me know what else you may need

**Comment by AdrianGarside** [comment] 2023-04-02 19:26
First look suggests this is the same root cause as the integration not handling being reloaded. Everything breaks and you need to restart home assistant to get it working again.

**Comment by AdrianGarside** [comment] 2023-04-02 19:34
2023-04-02 12:30:15.979 DEBUG (MainThread) [custom_components.bambu_lab] Async Setup Unload
2023-04-02 12:30:15.979 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Bambu P1P for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 626, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-02 12:30:15.983 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Bambu P1P for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 137, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-02 12:30:15.984 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Bambu P1P for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 72, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by AdrianGarside** [comment] 2023-04-02 22:34
Fixed with #70

**Closed** 2023-04-03 04:36 UTC
Labels: bug
