### ISSUE TITLE
[Feature] Translate HMS Errors

### ISSUE THREAD

**Issue by TobyStoe** [greghesp/ha-bambulab#390] opened 2024-01-03 20:48 UTC
### Describe the feature

It would be really cool, to translate the Error-Description from the HMS-Error Attributes.

Why?
When an Error occures, i broadcast a message via Alexa including the Description. Since the Description is always in english it sounds kina weird.

### What device is this for?

P1S

**Comment by AdrianGarside** [comment] 2024-11-18 02:09
Duplicate of #756

**Closed by AdrianGarside** 2024-11-18 02:09 UTC
Labels: feature request
