### ISSUE TITLE
[Bug] Failed to connect. Check credentials

### ISSUE THREAD

**Issue by Olli2k** [greghesp/ha-bambulab#732] opened 2024-11-12 13:09 UTC
### Home Assistant Version

2024.11.1

### Bambu Lab Integration Version

v2.0.34

### Describe the bug

When trying to connect to bambu lab cloud (Europe) I got the message, that connection is not possible. And that I should check my login creds. I don't know how to enable debug log with a not intsalled integration, but in general log I found this entry:

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.bambu_lab
Quelle: custom_components/bambu_lab/config_flow.py:164
Integration: Bambu Lab (Dokumentation, Probleme)
Erstmals aufgetreten: 13:47:45 (13 Vorkommnisse)
Zuletzt protokolliert: 14:00:57

Failed to connect with error code ('list index out of range',)

### To Reproduce

Setup
Integrations
Add Integration
Select Bambu Lab
Select Cloud
Select Europe
Enter Mail Address and Password
Click Login

### Expected Behaviour

Successful connection to Bambu Lab Cloud.

### What device are you using?

X1C

### Diagnostic Output

```shell
Not possible, first time installation
```

### Log Extracts

```shell
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.bambu_lab
Quelle: custom_components/bambu_lab/config_flow.py:164
Integration: Bambu Lab (Dokumentation, Probleme)
Erstmals aufgetreten: 13:47:45 (13 Vorkommnisse)
Zuletzt protokolliert: 14:00:57

Failed to connect with error code ('list index out of range',)
```

**Comment by myklek** [comment] 2024-11-12 13:12
Having same issue

**Comment by rebelthor** [comment] 2024-11-12 15:55
Same here on the latest `v2.0.34` version which contains some fixes around the area (#689)

**Comment by garv3** [comment] 2024-11-13 12:35
Yes, same for me as well. Cannot use the integration.
I seriously hate cloud services!

**Comment by JoshFink** [comment] 2024-11-13 15:12
Running into the same thing. North America connection. 

v2.0.34

`2024-11-13 10:09:25.150 ERROR (SyncWorker_26) [custom_components.bambu_lab.pybambu] CloudFlare blocked connection attempt
2024-11-13 10:09:25.152 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code ('list index out of range',)
2024-11-13 10:11:41.404 ERROR (SyncWorker_1) [custom_components.bambu_lab.pybambu] CloudFlare blocked connection attempt
2024-11-13 10:11:41.406 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code ('list index out of range',)
2024-11-13 10:11:45.994 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection (None)
`

**Comment by Ethzns** [comment] 2024-11-13 15:49
Also having this issue, exactly as described.

**Comment by BNEP** [comment] 2024-11-13 16:01
me too, here from central europe:
2024-11-13 16:56:07.132 ERROR (SyncWorker_6) [custom_components.bambu_lab.pybambu] CloudFlare blocked connection attempt
2024-11-13 16:56:07.133 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code ('list index out of range',)

**Comment by andrewmatten** [comment] 2024-11-13 16:07
I'm also experiencing the same issue

**Comment by jneilliii** [comment] 2024-11-13 18:22
> * Mimic browser behavior to access the endpoint.

this is what the latest updates in essence are doing by attempting to mimic a chrome browser with the curl_cffi module.

**Comment by jneilliii** [comment] 2024-11-13 19:33
Yeah, the curl_cffi changes were in the latest stable version but after release it seems cloudflare pivoted and started blocking it from what I've read.

**Comment by Yoanf26** [comment] 2024-11-13 19:39
Hello,

I'va just buy a P1S and it's not possible to connect with a cloud account

**Comment by mazdarx2001** [comment] 2024-11-13 23:27
Same here, first time user. However, I just re-logged into my Bambu account on my PC app. When logging in, it asked me "to keep my account secure, please put the code that was emailed". So even with 2FA turned off, it is now requiring me to authenticate with a number that is emailed to me. Possibly this is a Bambu labs thing, which then makes this integration not work since it doesn't work with 2FA????

**Comment by eric-faulkner** [comment] 2024-11-14 00:30
FWIW... same for me

**Comment by GregPeden** [comment] 2024-11-14 01:05
Confirmed same issue in North America. I used OAuth via google to sign up at first but I created a password on my account to enable HA integration.

**Comment by midormeepo** [comment] 2024-11-14 01:15
Same, also having this issue.

**Comment by oskari** [comment] 2024-11-14 06:48
I had this same issue yesterday, but today when trying again I could add my bambu printer.

**Comment by BNEP** [comment] 2024-11-14 08:03
Tested it again,
same here, now i can connect 👍 .

**Comment by mazdarx2001** [comment] 2024-11-14 13:21
Can confirm it works now too. Just added a printer and it needed a verification code which I entered and it worked! Don’t know what was wrong, but it works now

**Comment by eric-faulkner** [comment] 2024-11-14 17:56
Working for me, too.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by GregPeden** [comment] 2024-11-14 22:32
I can now get past the login/verification step but now it reports "No unconfigured printers found in the account."

**Comment by AdrianGarside** [comment] 2024-11-15 04:17
> I can now get past the login/verification step but now it reports "No unconfigured printers found in the account."

Please open a new issue with debug logs.

**Comment by AdrianGarside** [comment] 2024-11-15 04:19
> . So even with 2FA turned off, it is now requiring me to authenticate with a number that is emailed to me. Possibly this is a Bambu labs thing, which then makes this integration not work since it doesn't work with 2FA????

It's not full 2FA and the integration supports entering this code. What version are you running?

**Comment by AdrianGarside** [comment] 2024-11-15 04:20
Since the cloudflare issue has evaporated I'm going to close this issue. Please open a new issue for ongoing connection issues or if cloudflare starts blocking again.

**Closed by AdrianGarside** 2024-11-15 04:20 UTC
Labels: bug
