### ISSUE TITLE
[Feature] Expose P1P/S total print time

### ISSUE THREAD

**Issue by capsel22** [greghesp/ha-bambulab#419] opened 2024-01-09 20:00 UTC
### Describe the feature

with newest firmware, we can now see P1P/S' total print time on the screen.
Would it be possible to expose that to HA?

### What device is this for?

P1S

**Comment by AdrianGarside** [comment] 2024-01-09 22:12
Dupe of https://github.com/greghesp/ha-bambulab/issues/244

**Closed** 2024-01-09 22:13 UTC
Labels: feature request
