### ISSUE TITLE
[Bug] Cant open Camera Stream on X1C

### ISSUE THREAD

**Issue by BMOtheConsole** [greghesp/ha-bambulab#253] opened 2023-10-12 11:51 UTC
### Describe the bug

I cant see the Camera of my X1C in Home Assistant and getting the following Error:

Error from stream worker: Error opening stream (HTTP_UNAUTHORIZED, Server returned 401 Unauthorized (authorization failed)) rtsps://****:****@192.168.178.48/streaming/live/1

I have the "LAN Mode Liveview" On.

### To Reproduce

Open the Camera for the X1C in Home Assistant 

### Expected Behaviour

Show the Live Videofeed

### What device are you using?

X1C

### Diagnostic Output
[config_entry-bambu_lab-30e74fb946fcea346066ce69872a9943-2.json](https://github.com/greghesp/ha-bambulab/files/12893686/config_entry-bambu_lab-30e74fb946fcea346066ce69872a9943-2.json)

**Comment by BMOtheConsole** [comment] 2023-10-13 12:45
I added the Diagnostics File.

**Comment by BMOtheConsole** [comment] 2023-10-13 12:51
Does the Printer habe to be on for this to work?

**Comment by BMOtheConsole** [comment] 2023-10-13 12:56
Sorry, I did not know this. Now it should have all the Data

**Comment by berezovskyi-oleksandr** [comment] 2023-10-18 19:58
I observed a similar issue while using the Bambulab Cloud MQTT connection
Meanwhile, I can get the stream `rtsps://bblp:CODE@IP/streaming/live/1`, where CODE is the local access code from the printer. 

I suspect, that in the case of the cloud integration, the code tries to put the JWT token obtained during the authentication here

**Comment by mateuszdrab** [comment] 2023-10-21 13:25
> In my HA logs I get this error, dunno if it's related or just a symptom
> 
> ```
> Logger: homeassistant.components.stream.stream.camera.x1c_<serial>_camera
> Source: components/stream/__init__.py:431
> Integration: Stream (documentation, issues)
> First occurred: 1:03:22 PM (12 occurrences)
> Last logged: 1:14:22 PM
> 
> Error from stream worker: Error opening stream (PROTOCOL_NOT_FOUND, Protocol not found) ://bblp:<code>@disable
> ```

Same error here with a cloud connected X1C and the component configured via cloud MQTT (also tried local mode).

Isn't lan view same as lan only mode? I

**Comment by mateuszdrab** [comment] 2023-10-27 14:59
I did figure that out, I enabled Lan View but not Lan Mode. The error related to the camera is different so obviously, something's changed.

`Error from stream worker: Error opening stream (HTTP_UNAUTHORIZED, Server returned 401 Unauthorized (authorization failed)) rtsps://****:****@192.168.0.136/streaming/live/1`

**Comment by WolfwithSword** [comment] 2023-10-28 02:00
> I'm really struggling with this error. The printer is rejecting the username and password, but it makes no sense since it works because you've connected and got the sensors working

This could be related to the bug I sometimes had testing with the liveview - I find that the "first" boot of having it enabled, it doesn't work at all like this. You'll need to restart the printer after enabling it and then it usually works. Same thing after updating firmware, usually needs a reboot.

I've also found I can get some delays in it running if bambustudio is running with the camera before I access it via HA for the "first" time on a printer boot - though this is only one maybe 20% of the time, and it eventually works.

I assume it's not accidentally using a cloud-token password instead of access code? Because the HTTP unauthorized is very weird for the RTSPS stream... usually it's some timeout exception or rejection for other reasons.

Maybe it's worth debugging if @mateuszdrab could get it to work via a generic camera entity being manually added, or can access it using other software as they mentioned earlier?

**Comment by peterthepeter** [comment] 2023-11-06 14:03
I have the same problem, the camera of my X1C often hangs in HA and always has a delay of about 2-4 seconds. I use the access via Lan mode.
When I use the camera in Orca Slicer it works perfectly.

If you want me to provide any logs or similar, just let me know.

**Comment by mateuszdrab** [comment] 2023-11-10 22:42
I might have to try debugging it in some way.
I already tried restarting the printer after enabling lan view mode
I also tried using both local and cloud connections in the integration and it still experiences the unauthorized error.

What is the username and password that home assistant sends to the printer? I guess the password is the access code?

I wonder what would happen if I raised a support ticket on the Bambu app.

I'd really like to get the camera element to work, I keep glancing at my prints in the app but to be honest I'd want to just leave it streaming on my bedside tablet 😄

**Comment by mateuszdrab** [comment] 2023-11-11 13:10
> > I might have to try debugging it in some way. I already tried restarting the printer after enabling lan view mode I also tried using both local and cloud connections in the integration and it still experiences the unauthorized error.
> > 
> > What is the username and password that home assistant sends to the printer? I guess the password is the access code?
> > 
> > I wonder what would happen if I raised a support ticket on the Bambu app.
> > 
> > I'd really like to get the camera element to work, I keep glancing at my prints in the app but to be honest I'd want to just leave it streaming on my bedside tablet 😄
> 
> Username is `bblp` and the password is the access code your printer gives you.  You should be able to open it in VLC with `rtsps://bblp:<access code>@<ip address>/streaming/live/1` if its working.  If that fails, then there's definitely a firmware bug

Unfortunately no luck. 
Tried both rtsps and rtsp - both are trying to connect via UDP.

I noticed today that sometimes when I open the app on my phone, it takes a long time to start the stream and eventually reports a wrong auth code error. Then, I start the stream again and it works.
This points me to think it's a firmware bug.

**Comment by AdrianGarside** [comment] 2023-12-23 07:00
I'm going to resolve this as a dupe of #221. There isn't any known bugs in this integration at this time - all the issues seem to be firmware bugs on the Bambu side.

**Closed** 2023-12-24 05:16 UTC
Labels: bug, more info needed

**Comment by lukbe** [comment] 2024-07-03 05:43
Hello, I have with my X1C  and Home Assistant integration same problem = in the log is error Error from stream worker: Error opening stream. Exist a solution?
