### ISSUE TITLE
why does the camera work so badly?

### ISSUE THREAD

**Issue by man55** [greghesp/ha-bambulab#431] opened 2024-01-13 20:43 UTC
### Describe the bug

why does the camera work so badly?
After updating integration to the latest version, I was already glad that the camera was finally working. But the joy lasted for 10-20 minutes. And the camera froze again.
But even before it froze, the image was simply terrible, it felt like the video bitrate was several times less than the video I see in Bambu Studio.

### To Reproduce

.

### Expected Behaviour

A working camera with image quality like in a Bambu Studio.

### What device are you using?

X1C

### Diagnostic Output

```shell
.
```

### Other Information

All versions are latest.
Local connection.

**Comment by AdrianGarside** [comment] 2024-01-13 21:38
Dupe of #221. You’ll need to log an issue on the Bambu studio GitHub for it to get better.

The most reliable setup I’ve come up with is:
- go2rtc running in its own dedicated docker setup to proxy the x1 video feed.
- WebRTC with card telling it to use the external go2rtc
- Not using the camera from the integration.

The RTSP implementation on the X1 seems to be reasonably well behaved for the very first connection so as long as that never drops it keeps working. But any later connection attempts typically fail. But with the setup above my video now largely keeps working until that go2rtc gets restarted (eg if my HA host reboots) and then I need to reboot my X1 to get a working video feed again.

**Comment by AdrianGarside** [comment] 2024-01-13 22:01
I've heard the camera may be a bit more reliable with the new firmware that just dropped but I'm mid-upgrade to that so I haven't been able to test that myself.

**Comment by AdrianGarside** [comment] 2024-01-15 23:33
Closing as duplicate of #221

**Closed by AdrianGarside** 2024-01-15 23:33 UTC
Labels: bug
