### ISSUE TITLE
[Bug] When trying to log in via Bambu Cloud, I get the error Failed to connect. Check credentials.

### ISSUE THREAD

**Issue by Datastore24Kirill** [greghesp/ha-bambulab#701] opened 2024-11-07 07:53 UTC
### Describe the bug

When trying to log in via Bamboo Cloud, I get the error Failed to connect. Check credentials.
I use Chinese phone number authentication

![image](https://github.com/user-attachments/assets/c2d224be-53a3-47ad-8d5f-cbaa69464004)

### To Reproduce

1. Go to settings
2. Open Integrations
3. Click add integration
4. Select Bambu Lab
5. Enter phone number and password
6. Get an error

### Expected Behaviour

Successful authorization and the ability to select printers

### What device are you using?

P1S

### Diagnostic Output

```shell
[36m2024-11-07 10:52:45.778 DEBUG (SyncWorker_0) [custom_components.bambu_lab.pybambu] login()[0m
[36m2024-11-07 10:52:45.778 DEBUG (SyncWorker_0) [custom_components.bambu_lab.pybambu] Getting accessToken from Bambu Cloud[0m
[36m2024-11-07 10:52:46.609 DEBUG (SyncWorker_0) [custom_components.bambu_lab.pybambu] Did not understand json.[0m
[31m2024-11-07 10:52:46.610 ERROR (SyncWorker_0) [custom_components.bambu_lab.pybambu] Response not understood: <bound method Response.json of <Response [200]>>[0m
[36m2024-11-07 10:52:46.610 DEBUG (SyncWorker_0) [custom_components.bambu_lab.pybambu] Requested loginType: [0m
[31m2024-11-07 10:52:46.613 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code ('list index out of range',)[0m
```

**Comment by AdrianGarside** [comment] 2024-11-07 07:55
Please try this new version: https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.31

**Comment by AdrianGarside** [comment] 2024-11-07 07:56
Dupe of #686

**Closed by AdrianGarside** 2024-11-07 07:56 UTC
Labels: bug

**Comment by Datastore24Kirill** [comment] 2024-11-07 08:05
![image](https://github.com/user-attachments/assets/bda6e7e5-a24e-4367-a6b6-9717a610f635)

Chinese numbers don't have email, so apparently an SMS should arrive.

**Comment by Datastore24Kirill** [comment] 2024-11-07 08:06
I'll try to get an SMS code, if that solves the problem, I'll write in this thread.

**Comment by AdrianGarside** [comment] 2024-11-07 08:11
I was wondering if that might be the case when it decides a code is needed. It seems like that's not 100% guaranteed the way the one-time email code seems to now be for non-China email logins.

**Comment by AdrianGarside** [comment] 2024-11-07 08:12
Guess I will have to write some code distinguish phone numbers from emails so I can report the correct error text.

**Comment by Datastore24Kirill** [comment] 2024-11-07 08:33
> Думаю, мне придется написать какой-то код, отличающий номера телефонов от адресов электронной почты, чтобы я мог сообщить правильный текст ошибки или, может быть, просто изменить его на «электронная почта или смс».

I am ready to help with testing the login by phone number and SMS. I hope that all SMS will be sent to the phone with this authorization. It is strange that the code from the SMS is not required to enter Bambu Handy

**Comment by Datastore24Kirill** [comment] 2024-11-08 13:00
And....

![image](https://github.com/user-attachments/assets/05f86a76-acfb-4935-8c22-c169e833f81d)

`2024-11-08 15:58:11.055 DEBUG (SyncWorker_1) [custom_components.bambu_lab.pybambu] Getting accessToken from Bambu Cloud
2024-11-08 15:58:11.187 ERROR (SyncWorker_1) [custom_components.bambu_lab.pybambu] Login attempt failed with error code: 403
2024-11-08 15:58:11.187 DEBUG (SyncWorker_1) [custom_components.bambu_lab.pybambu] Response: '<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>

<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> bambulab.cn</h2>
      </div>
      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
              <span class="cf-no-screenshot error"></span>
          </div>
        </div>
      </div>
      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>
            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>
          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>
            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div>
      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">8df5bbab9d2fe314</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">81.5.84.10</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>
    </div>
  </div>
  <script>
  window._cf_translation = {};
</script>
<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'8df5bbab9d2fe314',t:'MTczMTA3MDY5MS4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body>
</html>
'
2024-11-08 15:58:11.190 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code (403,)`

**Comment by AdrianGarside** [comment] 2024-11-08 16:03
Sigh. Open a new issue but we may be fighting a losing battle. The curl_cffi approach is still working for me in north america.
