### ISSUE TITLE
[Bug] X1C Camera Stream Works After Printer Reboot Then Stops Soon After

### ISSUE THREAD

**Issue by jonhaber82** [greghesp/ha-bambulab#550] opened 2024-07-06 22:09 UTC
### Describe the bug

Not sure if this is the same issue as others have described but I noticed that my camera stream keeps not working, like nothing is displayed in the media modal and the play button is not enabled.

If I reboot the printer then the camera works for a bit (unsure exactly how long but not very long) and soon after the camera is unavailable until I reboot the printer again.

I can see the camera stream via the bambu app / bambu studio.

### To Reproduce

1. Click camera enty. Nothing is shown / No buttons are enabled. 

### Expected Behaviour

That the stream continues to work if it works after the machine is rebooted. 

### What device are you using?

X1C

### Diagnostic Output

```shell
2024-07-06 14:59:32.130 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.x1c_camera] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error, rtsps://****:****@192.168.1.38:322/streaming/live/1)
```

**Comment by AdrianGarside** [comment] 2024-07-07 17:08
Duplicate of #221.

**Closed by AdrianGarside** 2024-07-07 17:08 UTC
Labels: bug
