### ISSUE TITLE
[Bug] Failed to connect with error code ('list index out of range',)

### ISSUE THREAD

**Issue by dodancs** [greghesp/ha-bambulab#602] opened 2024-10-09 13:06 UTC
### Describe the bug

I am using P1S and since it does not yet allow offline firmware updates, I had to switch it back from LAN-only mode to cloud mode. I wanted to re-add it to HA, but when I want to log into my cloud account through the Bambulab HACS extension, I get the error "Failed to connect" or "Failed to connect. Check credentials", but the credentials are good.

Then I looked into HA logs, and saw the error coming from the Bambulab extension:
```
Logger: custom_components.bambu_lab
Source: custom_components/bambu_lab/config_flow.py:396
integration: Bambu Lab ([documentation](https://github.com/greghesp/ha-bambulab), [issues](https://github.com/greghesp/ha-bambulab/issues))
First occurred: 2:48:19 PM (6 occurrences)
Last logged: 2:55:59 PM

Failed to connect with error code ('list index out of range',)
```

### To Reproduce

1. Go to Settings -> Devices -> Bambu lab
2. Click on "Add entry"
3. Select "Bambu Cloud Configuration"
4. Select "Europe" and enter your credentials
5. Press "Next" and get the error

(Same thing happens when editing existing entry, switching it from LAN-only mode to cloud configuration)

### Expected Behaviour

I expect the extension to log me in, and allow me to set up the printer.

### What device are you using?

P1S

### Diagnostic Output

```shell
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.10.0",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Budapest",
    "os_name": "Linux",
    "os_version": "6.6.46-haos",
    "supervisor": "2024.10.0",
    "host_os": "Home Assistant OS 13.1",
    "docker_version": "26.1.4",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "sonoff": {
      "documentation": "https://github.com/AlexxIT/SonoffLAN",
      "version": "3.8.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "bambu_lab": {
      "documentation": "https://github.com/greghesp/ha-bambulab",
      "version": "2.0.22",
      "requirements": []
    },
    "pirateweather": {
      "documentation": "https://github.com/alexander0042/pirate-weather-ha",
      "version": "1.5.9",
      "requirements": [
        "python-forecastio==1.4.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "bambu_lab",
    "name": "Bambu Lab",
    "codeowners": [
      "greghesp",
      "AdrianGarside"
    ],
    "config_flow": true,
    "dependencies": [
      "device_automation",
      "ffmpeg",
      "mqtt"
    ],
    "documentation": "https://github.com/greghesp/ha-bambulab",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/greghesp/ha-bambulab/issues",
    "ssdp": [
      {
        "st": "urn:bambulab-com:device:3dprinter:1"
      }
    ],
    "version": "2.0.22",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 2.5049084797501564e-05
    },
    "efc74e9ff20af61fb9ec80b7414683e9": {
      "wait_import_platforms": -0.022955768974497914,
      "wait_base_component": -0.001062881899997592,
      "config_entry_setup": 0.04316708887927234,
      "config_entry_platform_setup": 0.00967454886995256
    }
  },
  "data": {
    "config_entry": {
      "created_at": "1970-01-01T00:00:00+00:00",
      "data": {
        "device_type": "P1S",
        "serial": "**REDACTED**"
      },
      "discovery_keys": {},
      "disabled_by": null,
      "domain": "bambu_lab",
      "entry_id": "efc74e9ff20af61fb9ec80b7414683e9",
      "minor_version": 1,
      "modified_at": "2024-10-09T12:30:07.054062+00:00",
      "options": {
        "region": "",
        "email": "",
        "username": "",
        "name": "",
        "host": "10.100.2.9",
        "local_mqtt": true,
        "auth_token": "",
        "access_code": "**REDACTED**",
        "usage_hours": 161.25000000000006
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "title": "**REDACTED**",
      "unique_id": null,
      "version": 2
    },
    "push_all": {
      "command": "clean_print_error",
      "print_error": 0,
      "sequence_id": "20015",
      "subtask_id": "0",
      "reason": "success",
      "result": "success"
    },
    "get_version": {
      "command": "get_version",
      "sequence_id": "0",
      "module": [
        {
          "name": "ota",
          "project_name": "C12",
          "sw_ver": "01.05.02.00",
          "hw_ver": "OTA",
          "sn": "**REDACTED**",
          "flag": 0
        },
        {
          "name": "esp32",
          "project_name": "C12",
          "sw_ver": "01.07.23.47",
          "hw_ver": "AP04",
          "sn": "**REDACTED**",
          "flag": 0
        },
        {
          "name": "mc",
          "project_name": "P1",
          "sw_ver": "00.00.22.39",
          "loader_ver": "00.00.00.23",
          "hw_ver": "MC07",
          "sn": "**REDACTED**",
          "flag": 0
        },
        {
          "name": "th",
          "project_name": "P1",
          "sw_ver": "00.00.07.12",
          "loader_ver": "00.00.00.14",
          "hw_ver": "TH09",
          "sn": "**REDACTED**",
          "flag": 0
        },
        {
          "name": "ams/0",
          "project_name": "",
          "sw_ver": "00.00.06.40",
          "loader_ver": "00.00.00.00",
          "ota_ver": "00.00.00.00",
          "hw_ver": "AMS08",
          "sn": "**REDACTED**",
          "flag": 0
        }
      ],
      "result": "success",
      "reason": ""
    }
  }
}
```

### Log Extracts

```shell
This error originated from a custom integration.

Logger: custom_components.bambu_lab
Source: custom_components/bambu_lab/config_flow.py:124
integration: Bambu Lab (documentation, issues)
First occurred: 2:53:16 PM (2 occurrences)
Last logged: 2:53:24 PM

Failed to connect with error code ('list index out of range',)

=================================================

This error originated from a custom integration.

Logger: custom_components.bambu_lab
Source: custom_components/bambu_lab/config_flow.py:396
integration: Bambu Lab (documentation, issues)
First occurred: 2:48:19 PM (6 occurrences)
Last logged: 2:55:59 PM

Failed to connect with error code ('list index out of range',)
```

### Other Information

Just in case, I have tried to log in to bambulab.com with the changed password as described in the first step of configuring the extension and I got in, so the password works. Not sure if it is an issue, but is not described anywhere, but I have TOTP/MFA enabled.

**Comment by AdrianGarside** [comment] 2024-10-21 01:59
This is a duplicate of the issue that having MFA enabled breaks the ability to use the integration.

**Closed by AdrianGarside** 2024-10-21 01:59 UTC
Labels: bug
