### ISSUE TITLE
[Bug] Version 1.4.9 fails to update statuses and throws multiple errors

### ISSUE THREAD

**Issue by sophof** [greghesp/ha-bambulab#191] opened 2023-09-10 10:42 UTC
### Describe the bug

It's a bit of a catch all, but this started after upgrading to 1.4.9, so I assume it is related.

Many - but not all - statuses are no longer updating, like print_status or bed_temperature. Others seem to update but not always. If I reload the integration all statuses are correctly updated at least once it seems. In addition I get the following errors:

```
This error originated from a custom integration.

Logger: custom_components.bambu_lab.pybambu
Source: custom_components/bambu_lab/pybambu/bambu_client.py:67
Integration: Bambu Lab (documentation, issues)
First occurred: 9 September 2023 at 21:38:17 (3 occurrences)
Last logged: 9 September 2023 at 21:38:17

An exception occurred processing a message:
Exception type: <class 'ValueError'>
Exception args: ("Sensor sensor.bambu_basic_print_status provides state value 'failed', which is not in the list of options provided",)
```

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:610
Integration: Sensor (documentation, issues)
First occurred: 9 September 2023 at 20:57:29 (30 occurrences)
Last logged: 9 September 2023 at 20:57:29

Platform bambu_lab does not generate unique IDs. ID 00M09A331400049_total_layers already exists - ignoring sensor.bambu_basic_total_layer_count
Platform bambu_lab does not generate unique IDs. ID 00M09A331400049_tray_now already exists - ignoring sensor.x1c_00m09a331400049_active_tray
Platform bambu_lab does not generate unique IDs. ID 00M09A331400049_gcode_file already exists - ignoring sensor.bambu_basic_gcode_filename
Platform bambu_lab does not generate unique IDs. ID 00M09A331400049_subtask_name already exists - ignoring sensor.bambu_basic_task_name
Platform bambu_lab does not generate unique IDs. ID 00M09A331400049_active_tray already exists - ignoring sensor.bambu_basic_active_tray
```

Note that the entities showing errors don't map one-to-one to those giving issues and that some of the 'unique_ID' sensors exist and some are shown `unavailable`.

### To Reproduce

Update integration to 1.4.9 and print something

### Expected Behaviour

Working, up-to-date-sensors

### What device are you using?

X1C

### Firmware Version

01.06.03.00 (AMS 00.00.06.32)

### Home Assistant Version

2023.9.1

### Component Version

1.4.9

### Log Extracts

```
This error originated from a custom integration.

Logger: custom_components.bambu_lab.pybambu
Source: custom_components/bambu_lab/pybambu/bambu_client.py:67
Integration: Bambu Lab (documentation, issues)
First occurred: 9 September 2023 at 21:38:17 (3 occurrences)
Last logged: 9 September 2023 at 21:38:17

An exception occurred processing a message:
Exception type: <class 'ValueError'>
Exception args: ("Sensor sensor.bambu_basic_print_status provides state value 'failed', which is not in the list of options provided",)
```

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:610
Integration: Sensor (documentation, issues)
First occurred: 9 September 2023 at 20:57:29 (30 occurrences)
Last logged: 9 September 2023 at 20:57:29

Platform bambu_lab does not generate unique IDs. ID 00M09A331400049_total_layers already exists - ignoring sensor.bambu_basic_total_layer_count
Platform bambu_lab does not generate unique IDs. ID 00M09A331400049_tray_now already exists - ignoring sensor.x1c_00m09a331400049_active_tray
Platform bambu_lab does not generate unique IDs. ID 00M09A331400049_gcode_file already exists - ignoring sensor.bambu_basic_gcode_filename
Platform bambu_lab does not generate unique IDs. ID 00M09A331400049_subtask_name already exists - ignoring sensor.bambu_basic_task_name
Platform bambu_lab does not generate unique IDs. ID 00M09A331400049_active_tray already exists - ignoring sensor.bambu_basic_active_tray
```

**Comment by man55** [comment] 2023-09-10 12:20
Installed last Version 1.4.9 today and can confirm, that a most of statuses are not updating for a long time..

**Comment by AdrianGarside** [comment] 2023-09-10 19:35
Are either of you running in lan mode or using any other software that connects to the local mqtt on the printer?

**Comment by AdrianGarside** [comment] 2023-09-10 19:36
@man55 do you have a P1P/S and are running in lan mode?

**Comment by AdrianGarside** [comment] 2023-09-10 19:58
Added the missing state which will address the first error.  I don't think that will cause  missing sensor updates - especially only some.

The second set of errors happens randomly but I haven't seen it / had it reported that it actually causes issues.

Fix for missing failed state:
https://github.com/greghesp/ha-bambulab/releases/tag/v1.4.10

**Comment by sophof** [comment] 2023-09-10 20:51
I'm on an X1C with LAN mode disabled. I agree they don't sound related, but I don't see any other errors.

**Comment by AdrianGarside** [comment] 2023-09-11 00:16
@sophof please let me know if you still see the problems with 1.4.11.

**Comment by man55** [comment] 2023-09-11 05:52
> @man55 do you have a P1P/S and are running in lan mode?
I'm on an X1C with LAN mode disabled.

**Comment by tretabyte** [comment] 2023-09-11 12:10
Hi,
I'm having the same issue with 1.4.11, not able to see much status update from Running to anything else.
I also detected another thing, when we Pause the print (and we are able to pause it from the integration), we can't resume it anymore, and button to resume gets pressed but nothing happens and I think it's because the status doesn't get updated therefore there's a conflit in resuming something that doesn't seem to be paused although the pause button worked.

**Comment by sophof** [comment] 2023-09-11 13:47
Currently running 1.4.11 with a test print and for me this solves it (somehow, I don't see anything relevant in the release notes). The sensors are updated and the unavailable sensors are available. A bit strange it isn't fixed for @tretabyte

**Comment by AdrianGarside** [comment] 2023-09-11 19:26
@man55 we'll need debug log output to diagnose your issue. It sounds a lot like the P1P/S specific issue with it's latest firmware but the X1 doesn't have that problem (yet AFAIK).

**Comment by AdrianGarside** [comment] 2023-09-11 19:26
@tretabyte what is your setup? X1 vs P1? Cloud vs Lan Mode?

**Comment by man55** [comment] 2023-09-11 20:30
> debug log output

I dont know where to get debug log output, sorry have not time to google..

**Comment by tretabyte** [comment] 2023-09-11 21:51
> @tretabyte what is your setup? X1 vs P1? Cloud vs Lan Mode?

Hi,
I'm using a X1C with Lan Mode ON

**Comment by AdrianGarside** [comment] 2023-09-12 00:19
For those still seeing this with 1.4.11 - what version of HomeAssistant are you running?

**Comment by tretabyte** [comment] 2023-09-12 01:46
easier this way
![image](https://github.com/greghesp/ha-bambulab/assets/60727013/d2f15eef-3b08-4ef2-90fb-2d45f8777434)

**Comment by Ali229** [comment] 2023-09-12 02:49
Having same issue where sensor don't update. Rolled back to 1.4.8 from 1.4.11 and everything is working as it used to. With 1.4.11 the print status was stuck on offline no matter what I tried.

**Comment by AdrianGarside** [comment] 2023-09-12 04:50
I need some debug logs in the failing state to see if it that sheds light on these symptoms since I cannot reproduce it. For anyone hitting this I also need to know:
HA version
Printer model
Whether the printer is in cloud mode or lan mode
If in cloud mode, whether you have other 'local' mqtt connections (e.g. P1Touch) to the printer.

**Comment by tretabyte** [comment] 2023-09-12 11:15
Hi
I'm trying to get some debug logs but in the meantime let me show you something.

This is the status on the printer:
![image](https://github.com/greghesp/ha-bambulab/assets/60727013/23d7161f-fac8-4192-aecb-5d8cf0abed61)

and this is what the integration is reporting:
![image](https://github.com/greghesp/ha-bambulab/assets/60727013/a84dc3fa-02e9-408d-a048-3459ff284381)

The lines highlighted are the ones that don«t update or take forever to get any change:
![image](https://github.com/greghesp/ha-bambulab/assets/60727013/750c96b5-9eca-4478-bea0-c750a7254217)

The printer is now running, it's printing the first layer of 150 but the info haven't changed yet (print above).
also the buttons to pause, resume, stop aren't working again:
![image](https://github.com/greghesp/ha-bambulab/assets/60727013/dadf7a57-e79e-4be9-8dac-b1090580785d)

**Comment by tretabyte** [comment] 2023-09-12 12:04
More details:
so I enabled DEBUG on logging and strangely not much was being dumped on logs (based on the screenshots above), this is all I got:
```
2023-09-12 11:16:20.986 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.x1c_00m09a341100337_camera] Error from stream worker: Error demuxing stream: [Errno 5] I/O error: 'rtsps://bblp:********@192.168.XXX.91/streaming/live/1'; last error log: [tls] Error decoding the received TLS packet.
2023-09-12 11:27:56.749 DEBUG (MainThread) [custom_components.bambu_lab] Camera RTSP Feed is rtsps://bblp:********@192.168.XXX.91/streaming/live/1
2023-09-12 11:32:10.757 DEBUG (MainThread) [custom_components.bambu_lab] Camera RTSP Feed is rtsps://bblp:********@192.168.XXX.91/streaming/live/1
2023-09-12 11:37:10.728 DEBUG (MainThread) [custom_components.bambu_lab] Camera RTSP Feed is rtsps://bblp:********@192.168.XXX.91/streaming/live/1
2023-09-12 11:42:10.609 DEBUG (MainThread) [custom_components.bambu_lab] Camera RTSP Feed is rtsps://bblp:********@192.168.XXX.91/streaming/live/1
2023-09-12 11:46:44.805 DEBUG (MainThread) [custom_components.bambu_lab] Camera RTSP Feed is rtsps://bblp:********@192.168.XXX.91/streaming/live/1
2023-09-12 12:06:39.349 DEBUG (MainThread) [custom_components.bambu_lab] Camera RTSP Feed is rtsps://bblp:********@192.168.XXX.91/streaming/live/1
2023-09-12 12:06:48.240 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.x1c_00m09a341100337_camera] Error from stream worker: Timestamp discontinuity detected: last dts = 191854, dts = 515968744
2023-09-12 12:09:21.805 DEBUG (MainThread) [custom_components.bambu_lab] Camera RTSP Feed is rtsps://bblp:********@192.168.XXX.91/streaming/live/1
2023-09-12 12:10:19.291 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.x1c_00m09a341100337_camera] Error from stream worker: Error demuxing stream: [Errno 5] I/O error: 'rtsps://bblp:********@192.168.XXX.91/streaming/live/1'; last error log: [tls] Error decoding the received TLS packet.
2023-09-12 12:12:10.953 DEBUG (MainThread) [custom_components.bambu_lab] Camera RTSP Feed is rtsps://bblp:********@192.168.XXX.91/streaming/live/1
2023-09-12 12:12:13.212 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.x1c_00m09a341100337_camera] Error from stream worker: Timestamp discontinuity detected: last dts = 8065043, dts = 523845008
2023-09-12 12:14:13.075 DEBUG (MainThread) [custom_components.bambu_lab] Camera RTSP Feed is rtsps://bblp:********@192.168.XXX.91/streaming/live/1
2023-09-12 12:14:14.398 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.x1c_00m09a341100337_camera] Error from stream worker: Timestamp discontinuity detected: last dts = 8014254, dts = 523792686
2023-09-12 12:18:51.551 DEBUG (MainThread) [custom_components.bambu_lab] Camera RTSP Feed is rtsps://bblp:********@192.168.XXX.91/streaming/live/1
2023-09-12 12:18:55.064 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.x1c_00m09a341100337_camera] Error from stream worker: Timestamp discontinuity detected: last dts = 2880, dts = 515780151
2023-09-12 12:39:48.605 DEBUG (MainThread) [custom_components.bambu_lab] Camera RTSP Feed is rtsps://bblp:********@192.168.XXX.91/streaming/live/1
2023-09-12 12:40:01.141 DEBUG (MainThread) [custom_components.bambu_lab] Camera RTSP Feed is rtsps://bblp:********@192.168.XXX.91/streaming/live/1
2023-09-12 12:40:02.014 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.x1c_00m09a341100337_camera] Error from stream worker: Timestamp discontinuity detected: last dts = 1122119, dts = 516895555
```
So I now did a full restart on HA and it seems, somehow, it "unstuck" whatever was preventing the updates to come through and now everything is updating just fine, I recall seeing this the last time I ran a print which means I'm almost sure that after this print finishes I'll see the same weird behavior as before, I'm attaching the debug log after restart.
[home-assistant_bambu_lab_2023-09-12T11-49-42.942Z.log](https://github.com/greghesp/ha-bambulab/files/12586112/home-assistant_bambu_lab_2023-09-12T11-49-42.942Z.log)

**Comment by man55** [comment] 2023-09-12 13:20
> I need some debug logs in the failing state to see if it that sheds light on these symptoms since I cannot reproduce it. For anyone hitting this I also need to know: HA version Printer model Whether the printer is in cloud mode or lan mode If in cloud mode, whether you have other 'local' mqtt connections (e.g. P1Touch) to the printer.

HA last version.
Printer X1C with AMS
Cloud mode on. Using Orca slicer and Bambu Handy for iOS.
No any other mqtt connections, how it possible?

**Comment by AdrianGarside** [comment] 2023-09-12 14:42
From #195, I think the likely problem in this case is another error of the form:
'`ValueError: Sensor sensor.x1c_00m09a360200242_print_status provides state value '', which is not in the list of options provided'

The addition of sensor localization support added the 'options' for those sensors that had known possible values so that they could be localized. And in every reported case where someone has reported an error in the logs like the above (including when I hit it first testing the localization changes after they were submitted for merge), the outcome seems to be somewhat permanent even if the sensor later is updated to have a known option.

**Comment by tretabyte** [comment] 2023-09-13 11:18
can confirmed that everything is getting updated with exception of 'Start time' which never changes from Unavailable

**Comment by AdrianGarside** [comment] 2023-09-13 14:30
"is it possible to get the small image preview of what's going to get printed?"

Possible, yes. But an expensive feature to implement. And on the P1* it would be making it do a lot of work (download the entire 3mf file off it via ftps) right as it's busy starting the print which could be too much for the ESP32 that runs it and interfere with printing.

**Comment by Ali229** [comment] 2023-09-13 14:39
The camera is still a hit or miss for me sometimes it works sometimes it doesn't randomly:
`Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtsps://****:****@192.168.0.59/streaming/live/1`

Not related to this issue but would love to have a small image, I think downloading the image right after the print starts(printer is heating, doing calibration) would be awesome, or better yet add a toggle in integration if the user wants to dl it or not.

**Comment by man55** [comment] 2023-09-13 17:06
The v1.4.12 worked fine for me too.

**Comment by AdrianGarside** [comment] 2023-09-13 18:37
Ok. I'm going to close this as fixed. Please let me know if you see the issue again. I will need debug logs to analyze it.

**Closed by AdrianGarside** 2023-09-13 18:37 UTC
Labels: bug, more info needed

**Comment by man55** [comment] 2023-09-14 14:23
On the second day, the sensor readings froze again and did not change.

**Comment by man55** [comment] 2023-09-14 14:24
> Ok. I'm going to close this as fixed. Please let me know if you see the issue again. I will need debug logs to analyze it.

How to get debug log?
Its stow working again (((
