### ISSUE TITLE
[Bug] Can't connect P1P in LAN Mode to HA

### ISSUE THREAD

**Issue by elec2** [greghesp/ha-bambulab#175] opened 2023-08-20 12:23 UTC
### Describe the bug
I try to add the Printer while it is on LAN mode. 
I switched from non LAN to LAN while the printer was added in HA, but no data was updated anymore so i deleted the printer and try'd to add him again. But it's not possible anymore.  

![image](https://github.com/greghesp/ha-bambulab/assets/46385991/91a5d4ee-bd5a-42f6-af88-96867f206db1)

### To Reproduce
1. Set Printer to LAN Mode
2. Add [ha-bambulab](https://github.com/greghesp/ha-bambulab) to HA
3. Add printer by typing Serial
4. Add IP + Accesscode

### Expected Behaviour

The integration should add the printer as device successfully. 

### What device are you using?

P1P

### Firmware Version

01.04.00.00

### Home Assistant Version

2023.8.3

### Component Version

1.4.8

### Log Extracts

2023-08-20 14:18:03.634 WARNING (Thread-13 (_thread_main)) [custom_components.bambu_lab.pybambu] On Disconnect: Disconnected from Broker: 0

### Other Information

When the printer is in non LAN mode it worked.

**Comment by elec2** [comment] 2023-08-20 12:40
Ok i found the reason and another problem:
I blocked the printer from having access to the internet (because i thought thats the reason of having a LAN only mode over all)
No the integration adds the printer but now I can see only 4 entities: Firmware, HMS Errors, Online, Recording Timelaps.

![image](https://github.com/greghesp/ha-bambulab/assets/46385991/4f1978df-f9df-452e-8fb3-39e214e6e864)

**Comment by elec2** [comment] 2023-08-20 12:48
Hm... I was waiting for some minutes and every other entitie is now visible while the firewall is active again. So... nevermind. 🤷

**Comment by elec2** [comment] 2023-08-20 19:44
Sorry but the problem is not fixed, it's crazy. After I started a new print, the infos are no longer updated even though there is no error in the logs. 
What still works is, for example, controlling the light.

**Comment by elec2** [comment] 2023-08-22 16:53
I switched back to cloud mode and everything is working just fine again. So it seems like the LAN mode is not working/supported atm!?

**Comment by AevumDecessus** [comment] 2023-08-27 18:54
It's possible your firewall is blocking access to the printer, the printer uses a completely different port in LAN only mode as it does in Cloud mode

**Comment by AdrianGarside** [comment] 2023-08-27 20:59
This is very likely a dupe of #174. Does restarting your printer before attempting the connection work?

**Comment by AdrianGarside** [comment] 2023-09-08 07:44
Closing as dupe of #174.

**Closed** 2023-09-08 07:44 UTC
Labels: bug
