### ISSUE TITLE
Multiple Connections to the Printer

### ISSUE THREAD

**Issue by akosin** [greghesp/ha-bambulab#186] opened 2023-09-08 01:16 UTC
This isn't really an issue with this integration, but I'm not sure where to ask this and I'm looking for some advice. I've been using this integration with Home Assistant for awhile and I love it. I recently wanted the try the P1 Touch ESP32 Touchscreen (https://github.com/xperiments/p1touch) but it seems to get all the controls and info instead of Home Assistant. Would there be anyway to use both?

**Comment by AdrianGarside** [comment] 2023-09-08 07:19
Duplicate of #174. Bambu broke multiple connections with the 1.0.4.0 P1P firmware. See that issue for more details and a link to the bambu github issue report.

**Closed by AdrianGarside** 2023-09-08 07:19 UTC

**Comment by AdrianGarside** [comment] 2023-09-17 17:33
@akosin the latest dev version has re-enabled the ability to connect via bambu cloud mqtt so you can now run this integration in bambu cloud mqtt mode and P1Touch (which will be local mqtt) simultaneously again with the latest P1P/S firmware.
